yakbak/views.py
from contextlib import suppress
from datetime import timedelta
from typing import Optional
import logging
import uuid

from dateutil.tz import tzoffset
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import login_required, login_user, logout_user
from flask_wtf import FlaskForm
from slugify import slugify
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.sql.expression import and_

from yakbak import mail
from yakbak.auth import get_magic_link_token_and_expiry, parse_magic_link_token
from yakbak.forms import (
    ConductReportForm,
    DemographicSurveyForm,
    EmailAddressForm,
    SpeakerEmailForm,
    TalkFeedbackForm,
    TalkForm,
    UserForm,
    VoteForm,
)
from yakbak.models import (
    Category,
    ConductReport,
    db,
    DemographicSurvey,
    InvitationStatus,
    Talk,
    TalkCategory,
    TalkFeedback,
    TalkSpeaker,
    TalkStatus,
    UsedMagicLink,
    User,
    Vote,
)
from yakbak.review import get_anonymous_review_csv
from yakbak.types import Response
from yakbak.view_helpers import (
    requires_new_proposal_window_open,
    requires_proposal_editing_window_open,
    requires_review_allowed,
    requires_voting_allowed,
)

app = Blueprint("views", __name__)
logger = logging.getLogger("views")


# per https://time.is/Anywhere_on_Earth
ANYWHERE_ON_EARTH = tzoffset("Anywhere on Earth", timedelta(hours=-12))


def load_talk(talk_id: int) -> Talk:
    talk = Talk.query.get_or_404(talk_id)
    if g.user not in [s.user for s in talk.speakers]:
        # TODO: figure out how to do this in the query directly?
        abort(404)
    if talk.conference != g.conference:
        # TODO: support multiple conferences
        abort(404)

    return talk


@app.route("/")
def index() -> Response:
    return render_template("index.html", aoe=ANYWHERE_ON_EARTH)


@app.route("/privacy")
def privacy_policy() -> Response:
    return render_template("privacy.html")


@app.route("/login")
def login() -> Response:
    auth_methods = current_app.settings.auth.auth_methods()
    return render_template("login.html", auth_methods=auth_methods)


@app.route("/logout")
def logout() -> Response:
    logout_user()
    return redirect(url_for("views.index"))


@app.route("/login/email", methods=["GET", "POST"])
def email_magic_link() -> Response:
    form = EmailAddressForm()
    if form.validate_on_submit():
        token, expiry = get_magic_link_token_and_expiry(form.email.data)
        url = url_for(
            "views.email_magic_link_login", magic_link_token=token, _external=True
        )
        mail.send_mail(
            to=[form.email.data],
            template="email/magic-link",
            magic_link=url,
            magic_link_expiration=expiry,
        )
        return redirect(url_for("views.email_magic_link_done"))
    return render_template("email_magic_link.html", form=form)


@app.route("/login/email/sent")
def email_magic_link_done() -> Response:
    return render_template("email_magic_link_sent.html")


@app.route("/login/token/<magic_link_token>")
def email_magic_link_login(magic_link_token: str) -> Response:
    try:
        used_magic_link = UsedMagicLink(token=magic_link_token)
        db.session.add(used_magic_link)
        db.session.commit()
    except IntegrityError:
        # race condition, UsedMagicLink row exists
        db.session.rollback()
        return current_app.response_class(
            render_template("email_magic_link_used.html"), status=401
        )

    verified_email = parse_magic_link_token(magic_link_token)
    if verified_email is None:
        abort(404)

    user = User.query.filter_by(email=verified_email).first()
    if user:
        login_user(user)
        return redirect(url_for("views.talks_list"))

    user = User(email=verified_email, fullname=verified_email)
    db.session.add(user)
    db.session.commit()
    login_user(user)
    flash("Welcome! Please tell us your name.")
    return redirect(url_for("views.user_profile"))


@app.route("/profile", methods=["GET", "POST"])
@login_required
def user_profile() -> Response:
    user = g.user
    form = UserForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("views.talks_list"))

    return render_template("profile.html", form=form)


@app.route("/talks")
@login_required
def talks_list() -> Response:
    talks = [ts.talk for ts in g.user.talks if ts.state == InvitationStatus.CONFIRMED]
    this_conf_talks = [t for t in talks if t.conference == g.conference]
    proposed_talks = [t for t in this_conf_talks if t.state == TalkStatus.PROPOSED]
    withdrawn_talks = [t for t in this_conf_talks if t.state == TalkStatus.WITHDRAWN]

    invitations = TalkSpeaker.query.filter(
        TalkSpeaker.user == g.user,
        TalkSpeaker.state != InvitationStatus.CONFIRMED,
        TalkSpeaker.state != InvitationStatus.DELETED,
        Talk.conference == g.conference,
    ).all()
    speaker_actions = {
        InvitationStatus.PENDING: [
            ("Reject", "danger", "views.reject_invite"),
            ("Accept", "primary", "views.accept_invite"),
        ],
        InvitationStatus.REJECTED: [("Accept", "primary", "views.accept_invite")],
    }
    talk_actions = {
        TalkStatus.PROPOSED: [("Withdraw", "danger", "views.withdraw_proposal")]
    }
    if g.conference.creating_proposals_allowed:
        # you can resubmit talks only until the end of the CFP window
        talk_actions[TalkStatus.WITHDRAWN] = [
            ("Re-Submit", "primary", "views.resubmit_proposal")
        ]

    prompt_for_survey = proposed_talks and not g.user.demographic_survey
    prompt_for_bio = proposed_talks and not g.user.speaker_bio
    return render_template(
        "talks_list.html",
        proposed_talks=proposed_talks,
        withdrawn_talks=withdrawn_talks,
        num_talks=len(proposed_talks),
        invitations=invitations,
        speaker_actions=speaker_actions,
        talk_actions=talk_actions,
        prompt_for_survey=prompt_for_survey,
        prompt_for_bio=prompt_for_bio,
        TalkStatus=TalkStatus,
    )


@app.route("/talks/<int:talk_id>", methods=["GET", "POST"])
@login_required
def edit_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    form = TalkForm(conference=g.conference, obj=talk)
    if form.validate_on_submit():
        form.populate_obj(talk)
        should_save = (
            g.conference.editing_proposals_allowed
            or not talk.has_voter_visible_content_changes()
        )
        if not should_save:
            resp = render_template("action_not_allowed.html", action="edit_proposal")
            return resp, 400

        talk.reset_after_edits()
        db.session.add(talk)
        db.session.commit()
        return redirect(url_for("views.preview_talk", talk_id=talk.talk_id))

    return render_template("edit_talk.html", talk=talk, form=form)


@app.route("/talks/<int:talk_id>/anonymized", methods=["GET", "POST"])
@login_required
def anonymized_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    if not talk.is_anonymized:
        flash("This talk has not yet been anonymized for review")

    return render_template("anonymized_talk_preview.html", talk=talk)


@app.route("/talks/<int:talk_id>/withdraw")
@login_required
def withdraw_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.WITHDRAWN
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} withdrawn")
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/resubmit")
@login_required
@requires_new_proposal_window_open
def resubmit_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.PROPOSED
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} re-submitted")
    return redirect(url_for("views.talks_list"))


@app.route("/vote")
@login_required
@requires_voting_allowed
def vote_home() -> Response:
    """Render the voting homepage with talk categories."""
    # TODO: When this is multitenant, categories and votes should be filtered
    # by event.
    categories = Category.query.filter_by(conference=g.conference).order_by(
        Category.name.asc()
    )
    # TODO: This is an inefficient way to do this. Write it as one query
    # instead.
    categories_counts = {
        category: Talk.query.join(TalkCategory)
        .filter(
            Talk.state == TalkStatus.PROPOSED,
            Talk.talk_id.notin_(
                db.session.query(Vote.talk_id).filter(
                    Vote.user == g.user, Vote.value != None  # noqa: E711
                )
            ),
            TalkCategory.category_id == category.category_id,
        )
        .count()
        for category in categories
    }

    votes = Vote.query.filter(
        Vote.user == g.user, Vote.talk.has(conference=g.conference)
    ).order_by(Vote.created.asc())
    return render_template(
        "vote/home.html",
        categories_counts=categories_counts,
        clear_skipped_form=FlaskForm(),
        votes=votes,
        vote_label_map=VoteForm.VOTE_VALUE_CHOICES,
    )


@app.route("/vote/category/<int:category_id>")
@login_required
@requires_voting_allowed
def vote_choose_talk_from_category(category_id: int) -> Response:
    """Display a talk in need of a vote.

    If a talk has already been displayed for voting and is included in
    the selected category, but has not been voted on or explicitly
    skipped, it should be used. This is independent of the chosen
    category.  Otherwise choose fairly from a list of possible talks.

    The talk list:

    1. is filtered down to the requested category

yakbak/templates/vote/detail.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Vote on "{{ talk.anonymized_title }}" - {{ super() }}{% endblock %}

{% block morestyles %}
<style>
  form li {
    list-style-type: none;
  }
  form li input, form li label {
    display: inline;
  }
  {# FIXME: This form-control style is a hack, likely due to a bootstrap upgrade. This should be fixed properly. #}
  ul.form-control {
    height: auto;
  }
</style>
{% endblock %}

{% block container %}
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col"><h1>{{ talk.anonymized_title }}</h1></div>
      <div class="w-100"></div>
      <div class="col"><h4>{{ talk.talk_format.display_name() }}</h2></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col">
        {{ talk.anonymized_description|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Outline:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.anonymized_outline|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Audience Take-Aways:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.anonymized_take_aways|markdown }}
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    {% if g.conference.voting_allowed %}
    <p>Should this talk be presented at {{ g.conference.informal_name }}?</p>
    {% if show_vote_form %}
      <form method="POST">
        {{ form.hidden_tag() }}
        {{ macros.render_error(form.action) }}
        {{ macros.render_error(form.value) }}
        {{ macros.render_field(form.value) }}
        <button type="submit" class="btn btn-primary" name="action" value="vote">Vote</button>
        <button type="submit" class="btn btn-light border" name="action" value="skip">Skip</button>
      </form>
    {% else %}
      {% if vote is none %}
      <p>You did not vote on this talk.</p>
      {% elif vote.value is not none %}
      <p>You voted: {{ vote_names[vote.value] }}</p>
      {% else %}
      <p>You skipped voting on this talk.</p>
      {% endif %}
      <hr>
    {% endif %}
    {% endif %}


    <p>If this proposal presents a code of conduct issue, please let the conduct team know.</p>
    <form method="POST" action="{{ url_for("views.conduct_report") }}">
      {{ conduct_form.hidden_tag() }}
      {{ macros.render_field(conduct_form.text, placeholder="The talk proposal presents a code of conduct issue because...") }}
      {{ macros.render_field(conduct_form.anonymous) }}
      <button type="submit" class="btn btn-primary btn-warning">Report</button>
    </form>

    {% if g.user.site_admin %}
    <hr>
    <p>Speaker feedback:</p>
    {% if g.conference.voting_allowed %}
    <p><em>New feedback cannot be sent to speakers during the voting window (speakers can not edit their proposal at this time)</em></p>
    {% else %}
    {{ macros.render_speaker_feedback_form(talk, feedback_form) }}
    <hr>
    {% endif %}

    {{ macros.render_past_feedback(talk) }}
    {% endif %}
  </div>
</div>
{% endblock %}

yakbak/templates/vote/home.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Categories - {{ super() }}{% endblock %}

{% block container %}
<h3 class="float-left">Talk Categories</h3>
<form class="float-md-right" method="POST" action="{{ url_for("views.clear_skipped_votes") }}">
  {{ clear_skipped_form.hidden_tag() }}
  <button type="submit" class="btn btn-primary">Clear Skipped Votes</button>
</form>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Category</th>
      <th scope="col">Talks Remaining</th>
    </tr>
  </thead>
  <tbody>
    {% for category, count in categories_counts.items() %}
      <tr>
        <td>
          <a href="{{ url_for("views.vote_choose_talk_from_category", category_id=category.category_id) }}">
            {{ category.name }}
          </a>
        </td>
        <td>
          {{ count }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<h3>My Votes</h3>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Talk</th>
      <th scope="col">Vote</th>
    </tr>
  </thead>
  <tbody>
    {% for vote in votes %}
      <tr>
        <td><a href="{{ url_for("views.vote", public_id=vote.public_id) }}">{{ vote.talk.title }}</a></td>
        <td>
          {{ macros.render_vote(vote, vote_label_map) }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}