yakbak/views.py
from contextlib import suppress
from datetime import timedelta
from typing import Optional
import logging
import uuid

from dateutil.tz import tzoffset
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import login_required, login_user, logout_user
from flask_wtf import FlaskForm
from slugify import slugify
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.sql.expression import and_

from yakbak import mail
from yakbak.auth import get_magic_link_token_and_expiry, parse_magic_link_token
from yakbak.forms import (
    ConductReportForm,
    DemographicSurveyForm,
    EmailAddressForm,
    SpeakerEmailForm,
    TalkFeedbackForm,
    TalkForm,
    UserForm,
    VoteForm,
)
from yakbak.models import (
    Category,
    ConductReport,
    db,
    DemographicSurvey,
    InvitationStatus,
    Talk,
    TalkCategory,
    TalkFeedback,
    TalkSpeaker,
    TalkStatus,
    UsedMagicLink,
    User,
    Vote,
)
from yakbak.review import get_anonymous_review_csv
from yakbak.types import Response
from yakbak.view_helpers import (
    requires_new_proposal_window_open,
    requires_proposal_editing_window_open,
    requires_review_allowed,
    requires_voting_allowed,
)

app = Blueprint("views", __name__)
logger = logging.getLogger("views")


# per https://time.is/Anywhere_on_Earth
ANYWHERE_ON_EARTH = tzoffset("Anywhere on Earth", timedelta(hours=-12))


def load_talk(talk_id: int) -> Talk:
    talk = Talk.query.get_or_404(talk_id)
    if g.user not in [s.user for s in talk.speakers]:
        # TODO: figure out how to do this in the query directly?
        abort(404)
    if talk.conference != g.conference:
        # TODO: support multiple conferences
        abort(404)

    return talk


@app.route("/")
def index() -> Response:
    return render_template("index.html", aoe=ANYWHERE_ON_EARTH)


@app.route("/privacy")
def privacy_policy() -> Response:
    return render_template("privacy.html")


@app.route("/login")
def login() -> Response:
    auth_methods = current_app.settings.auth.auth_methods()
    return render_template("login.html", auth_methods=auth_methods)


@app.route("/logout")
def logout() -> Response:
    logout_user()
    return redirect(url_for("views.index"))


@app.route("/login/email", methods=["GET", "POST"])
def email_magic_link() -> Response:
    form = EmailAddressForm()
    if form.validate_on_submit():
        token, expiry = get_magic_link_token_and_expiry(form.email.data)
        url = url_for(
            "views.email_magic_link_login", magic_link_token=token, _external=True
        )
        mail.send_mail(
            to=[form.email.data],
            template="email/magic-link",
            magic_link=url,
            magic_link_expiration=expiry,
        )
        return redirect(url_for("views.email_magic_link_done"))
    return render_template("email_magic_link.html", form=form)


@app.route("/login/email/sent")
def email_magic_link_done() -> Response:
    return render_template("email_magic_link_sent.html")


@app.route("/login/token/<magic_link_token>")
def email_magic_link_login(magic_link_token: str) -> Response:
    try:
        used_magic_link = UsedMagicLink(token=magic_link_token)
        db.session.add(used_magic_link)
        db.session.commit()
    except IntegrityError:
        # race condition, UsedMagicLink row exists
        db.session.rollback()
        return current_app.response_class(
            render_template("email_magic_link_used.html"), status=401
        )

    verified_email = parse_magic_link_token(magic_link_token)
    if verified_email is None:
        abort(404)

    user = User.query.filter_by(email=verified_email).first()
    if user:
        login_user(user)
        return redirect(url_for("views.talks_list"))

    user = User(email=verified_email, fullname=verified_email)
    db.session.add(user)
    db.session.commit()
    login_user(user)
    flash("Welcome! Please tell us your name.")
    return redirect(url_for("views.user_profile"))


@app.route("/profile", methods=["GET", "POST"])
@login_required
def user_profile() -> Response:
    user = g.user
    form = UserForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("views.talks_list"))

    return render_template("profile.html", form=form)


@app.route("/talks")
@login_required
def talks_list() -> Response:
    talks = [ts.talk for ts in g.user.talks if ts.state == InvitationStatus.CONFIRMED]
    this_conf_talks = [t for t in talks if t.conference == g.conference]
    proposed_talks = [t for t in this_conf_talks if t.state == TalkStatus.PROPOSED]
    withdrawn_talks = [t for t in this_conf_talks if t.state == TalkStatus.WITHDRAWN]

    invitations = TalkSpeaker.query.filter(
        TalkSpeaker.user == g.user,
        TalkSpeaker.state != InvitationStatus.CONFIRMED,
        TalkSpeaker.state != InvitationStatus.DELETED,
        Talk.conference == g.conference,
    ).all()
    speaker_actions = {
        InvitationStatus.PENDING: [
            ("Reject", "danger", "views.reject_invite"),
            ("Accept", "primary", "views.accept_invite"),
        ],
        InvitationStatus.REJECTED: [("Accept", "primary", "views.accept_invite")],
    }
    talk_actions = {
        TalkStatus.PROPOSED: [("Withdraw", "danger", "views.withdraw_proposal")]
    }
    if g.conference.creating_proposals_allowed:
        # you can resubmit talks only until the end of the CFP window
        talk_actions[TalkStatus.WITHDRAWN] = [
            ("Re-Submit", "primary", "views.resubmit_proposal")
        ]

    prompt_for_survey = proposed_talks and not g.user.demographic_survey
    prompt_for_bio = proposed_talks and not g.user.speaker_bio
    return render_template(
        "talks_list.html",
        proposed_talks=proposed_talks,
        withdrawn_talks=withdrawn_talks,
        num_talks=len(proposed_talks),
        invitations=invitations,
        speaker_actions=speaker_actions,
        talk_actions=talk_actions,
        prompt_for_survey=prompt_for_survey,
        prompt_for_bio=prompt_for_bio,
        TalkStatus=TalkStatus,
    )


@app.route("/talks/<int:talk_id>", methods=["GET", "POST"])
@login_required
def edit_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    form = TalkForm(conference=g.conference, obj=talk)
    if form.validate_on_submit():
        form.populate_obj(talk)
        should_save = (
            g.conference.editing_proposals_allowed
            or not talk.has_voter_visible_content_changes()
        )
        if not should_save:
            resp = render_template("action_not_allowed.html", action="edit_proposal")
            return resp, 400

        talk.reset_after_edits()
        db.session.add(talk)
        db.session.commit()
        return redirect(url_for("views.preview_talk", talk_id=talk.talk_id))

    return render_template("edit_talk.html", talk=talk, form=form)


@app.route("/talks/<int:talk_id>/anonymized", methods=["GET", "POST"])
@login_required
def anonymized_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    if not talk.is_anonymized:
        flash("This talk has not yet been anonymized for review")

    return render_template("anonymized_talk_preview.html", talk=talk)


@app.route("/talks/<int:talk_id>/withdraw")
@login_required
def withdraw_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.WITHDRAWN
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} withdrawn")
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/resubmit")
@login_required
@requires_new_proposal_window_open
def resubmit_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.PROPOSED
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} re-submitted")
    return redirect(url_for("views.talks_list"))


@app.route("/vote")
@login_required
@requires_voting_allowed
def vote_home() -> Response:
    """Render the voting homepage with talk categories."""
    # TODO: When this is multitenant, categories and votes should be filtered
    # by event.
    categories = Category.query.filter_by(conference=g.conference).order_by(
        Category.name.asc()
    )
    # TODO: This is an inefficient way to do this. Write it as one query
    # instead.
    categories_counts = {
        category: Talk.query.join(TalkCategory)
        .filter(
            Talk.state == TalkStatus.PROPOSED,
            Talk.talk_id.notin_(
                db.session.query(Vote.talk_id).filter(
                    Vote.user == g.user, Vote.value != None  # noqa: E711
                )
            ),
            TalkCategory.category_id == category.category_id,
        )
        .count()
        for category in categories
    }

    votes = Vote.query.filter(
        Vote.user == g.user, Vote.talk.has(conference=g.conference)
    ).order_by(Vote.created.asc())
    return render_template(
        "vote/home.html",
        categories_counts=categories_counts,
        clear_skipped_form=FlaskForm(),
        votes=votes,
        vote_label_map=VoteForm.VOTE_VALUE_CHOICES,
    )


@app.route("/vote/category/<int:category_id>")
@login_required
@requires_voting_allowed
def vote_choose_talk_from_category(category_id: int) -> Response:
    """Display a talk in need of a vote.

    If a talk has already been displayed for voting and is included in
    the selected category, but has not been voted on or explicitly
    skipped, it should be used. This is independent of the chosen
    category.  Otherwise choose fairly from a list of possible talks.

    The talk list:

    1. is filtered down to the requested category

yakbak/templates/action_not_allowed.html
{% extends "base.html" %}

{% block container %}
<div class="row">
  <div class="col">
    {% if action == "create_proposal" or action == "edit_proposal" %}
    <h2>{{ g.conference.informal_name }} CFP is Over</h2>
    <p>
    Unfortunately, the {{ g.conference.informal_name }} call for proposals
    is over. We appreciate your interest, but we cannot accept new proposals
    at this time.
    </p>
    {% if action == "edit_proposal" %}
    <p>
    Additionally, talk editing is disabled at this time while we review
    talks for selection in {{ g.conference.informal_name }}.
    </p>
    {% endif %}
    {% endif %}
    {% if action == "vote" %}
    <h2>
      {{ g.conference.informal_name }} Voting has
      {% if g.conference.voting_window_after_now %}
        not started yet
      {% else %}
        ended
      {% endif %}
    </h2>

    <p>
    Unfortunately, voting on proposals for {{ g.conference.informal_name }} has
    ended. We appreciate the time that you have taken to vote so far. Your input
    helps us make {{ g.conference.informal_name }} as good as it can be!
    </p>
    {% endif %}
    {% if action == "review" %}
    {% if g.conference.review_window_after_now %}
    <h2>{{ g.conference.informal_name }} Voting Review Has Not Started</h2>
    <p>
    Unfortunately, the {{ g.conference.informal_name }} vote review period
    has not started yet.
    </p>
    {% else %}
    <h2>{{ g.conference.informal_name }} Voting Review Is Over</h2>
    <p>
    Unfortunately, the {{ g.conference.informal_name }} vote review period
    has finished.
    </p>
    {% endif %}
    {% endif %}
    <p>
    <a class="btn btn-primary" href="{{ url_for("views.talks_list") }}">Back to talks list</a>
    </p>
  </div>
</div>
{% endblock %}

yakbak/templates/base.html
{# Modified from base.html in flask_bootstrap4 #}
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block metas %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {%- endblock metas %}

    {%- block head %}
    <title>{% block title %}{{ g.conference.informal_name }}{% endblock %}</title>
    <link rel="icon" href="{{ url_for("static", filename="favicon.png") }}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for("static", filename="site.css") }}">
    {% block morestyles %}
    {%- endblock morestyles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for("views.index") }}">{{ g.conference.informal_name }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% for label, url, active in left_nav %}
            <li class="nav-item{% if active %} active{% endif %}">
              <a class="nav-link" href="{{ url }}">{{ label }}{% if active %} <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
            {% endfor %}
          </ul>
          <ul class="navbar-nav">
            {% for label, url, active in right_nav %}
            <li class="nav-item{% if active %} active{% endif %}">
              <a class="nav-link" href="{{ url }}">{{ label }}{% if active %} <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </nav>
    {%- endblock navbar %}

    {% block content %}
    {% set messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    <div class="container pt-3">
      {% for category, message in messages %}
      <div class="{%- if category == 'warning' -%}
      alert-warning
      {%- elif category == 'error' -%}
      alert-danger
      {%- else -%}
      alert-info
      {%- endif %} alert">
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <div class="main-container container pt-3">
      {% block container %}
      <div class="row">
        <div class="col">{% block main %}{% endblock %}</div>
      </div>
      {% endblock %}
    </div>
    {%- endblock content %}

    {% block footer %}
    <footer class="footer bg-light">
      <div class="container text-muted">
        <p>{{ g.conference.footer_text|markdown }}</p>
        <p>
          Copyright &copy; 2019 - {{ datetime.utcnow().year }} Big Apple Py, Inc.
          <a href="{{ url_for("views.privacy_policy") }}">Privacy Policy</a>
        </p>
        <p>
          Have a question about the {{ g.conference.informal_name }} call for proposals?
          Email <a href="mailto:{{ g.conference.cfp_email }}">{{ g.conference.cfp_email }}</a>.
        <p>
          Spot a problem? Let the developers know at
          <a href="https://gitlab.com/bigapplepy/yak-bak">https://gitlab.com/bigapplepy/yak-bak</a>.
        </p>
      </div>
    </footer>
    {% endblock footer %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

yakbak/templates/demographic_survey.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Demographic Survey - {{ super() }}{% endblock %}

{% block morestyles %}
{{ super() }}
<style type="text/css">
  ul {
    padding: 0;
  }
  ul li {
    list-style-type: none;
  }
  ul input[type="checkbox"] {
    display: inline;
    width: auto;
  }
  ul li input[type="text"] {
    display: inline-block;
    width: 80%;
  }
  input[type="checkbox"] + label {
    display: inline;
  }
  ul.multi-select li {
    margin-bottom: 0.5rem;
  }
</style>
{% endblock %}

{% block container %}
<form method="post" class="pb-3">
  <div class="row">
    <div class="col-md-8">
      <h1>PyGotham Demographic Survey</h1>
      <p>
      {{ g.conference.full_name }} is committed to creating a welcoming and
      inclusive environment for people of all backgrounds. We actively seek to
      increase the diversity of our attendees and speakers. In order to help
      measure and improve our efforts in this area, we are asking speakers to
      help us by completing this form. The
      <a href="https://2021.pygotham.tv/about/diversity/">PyGotham
      website</a> has more about our diversity efforts and how we will use this
      information.
      </p>

      <p>
      All answers are optional, and will only be accessible to the PyGotham
      organizers in order to ensure a diverse and awesome conference. We will
      never make individual answers public, but we may publish aggregate
      statistics based on this survey.
      </p>

      <p>If you do not wish to be prompted to fill out the survey again,
      you may <a href="{{ url_for("views.demographic_survey_opt_out") }}">opt
      out</a>.
      </p>

    </div>
  </div>
  <div class="row">
    {% set field = form["gender"] %}
    <div class="col-md-8 form-group">
      <h4>{{ macros.render_label(field, "I am a:") }}</h4>
      <p><small>Choose all that apply.</small></p>
      {{ macros.render_field(field) }}
    </div>
  </div>

  <div class="row">
    {% set field = form["ethnicity"] %}
    <div class="col-md-8 form-group">
      <h4>{{ macros.render_label(field, "My ethnicity is:") }}</h4>
      <p><small>Choose all that apply.</small></p>
      {{ macros.render_field(field) }}
    </div>
  </div>

  <div class="row">
    {% set field = form["past_speaking"] %}
    <div class="col-md-8 form-group">
      <h4>{{ macros.render_label(field, "About my past speaking experience:") }}</h4>
      <p><small>Choose all that apply.</small></p>
      {{ macros.render_field(field) }}
    </div>
  </div>
  <div class="row">
    {% set field = form["age_group"] %}
    <div class="col-md-8 form-group">
      <h4>{{ macros.render_label(field, "My age is:") }}</h4>
      {{ macros.render_field(field, class_="") }}
    </div>
  </div>
  <div class="row">
    {% set field = form["programming_experience"] %}
    <div class="col-md-8 form-group">
      <h4>{{ macros.render_label(field, "I have been programming for:") }}</h4>
      <p><small>Include all programming experience in any language, not only Python.</small></p>
      {{ macros.render_field(field, class_="") }}
    </div>
  </div>
  <div class="row">
    <div class="col-md-auto">
      <button type="submit" class="btn btn-primary" style="min-width: 7em">Save</button>
    </div>
    <div class="col-md-6">
      <small id="{{ field.id }}-help" class="form-text text-muted" style="margin-top:0">
        The demographic information collected here is entirely optional. If you wish,
        you may <a href="{{ url_for("views.demographic_survey_opt_out") }}">opt out</a>
        of the survey. If you change your mind, you can always return here from your
        <a href="{{ url_for("views.user_profile") }}">profile</a>.
      </small>
    </div>
  </div>
  {{ form["csrf_token"] }}
</form>
{% endblock %}

yakbak/templates/demographic_survey_done.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Demographic Survey - {{ super() }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-md-8">
    {% if optout %}
    <h1>You Have Opted Out of the PyGotham Demographic Survey</h1>
    <p>
    If you change your mind, you can always return here from your
    <a href="{{ url_for("views.user_profile") }}">profile</a>
    </p>
    {% else %}
    <h1>Thanks For Completing the PyGotham Demographic Survey</h1>
    <p>
    You can always edit your responses from your
    <a href="{{ url_for("views.user_profile") }}">profile</a>.
    </p>
    {% endif %}
</div>
{% endblock %}

yakbak/templates/email_magic_link_sent.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Request Login Link - {{ super() }}{% endblock %}

{% block container %}
<p>We have sent a link to you, and it should be arriving soon. Once it does,
just click it to return here and log in!</p>
{% endblock %}

yakbak/templates/email_magic_link_used.html
{% extends "base.html" %}

{% block title %}Invalid Login Link - {{ super() }}{% endblock %}

{% block container %}
<p>
That magic link is invalid. You can <a href="{{ url_for("views.email_magic_link") }}">create another</a>
or <a href="{{ url_for("views.login") }}">choose another login method</a>.
</p>
{% endblock %}

yakbak/templates/preview_talk.html
{% extends "base.html" %}

{% block title %}Preview "{{ talk.title|default("Talk") }}" - {{ super() }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col"><h1>{{ talk.title }}</h1></div>
      <div class="w-100"></div>
      <div class="col"><h4>{{ talk.talk_format.display_name() }}</h2></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col">
        {{ talk.description|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Outline:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.outline|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Audience Take-Aways:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.take_aways|markdown }}
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <em class="text-muted">Reviewers will see voting instructions here.</em>
  </div>
</div>
<div class="row py-3">
  <div class="col">
    <a class="btn btn-primary" href="{{ url_for("views.talks_list") }}">Save &amp; Return</a> or
    <a class="btn btn-light border" href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">Edit Again</a>
  </div>
</div>
{% endblock %}

yakbak/templates/talks_list.html
{% extends "base.html" %}

{% block title %}Talks - {{ super() }}{% endblock %}

{% macro vitals(talk) %}
{% set speakers = talk.speakers|map(attribute="user") %}
{% set other_speakers = speakers|remove(user)|map(attribute="fullname")|list %}
{% if other_speakers|length > 1 %}
({{ talk.talk_format.display_name() }}, {{ other_speakers|join(", ") }}, and You)
{% elif other_speakers|length == 1 %}
({{ talk.talk_format.display_name() }}, {{ other_speakers|join("") }} and You)
{% else %}
({{ talk.talk_format.display_name() }})
{% endif %}
{% endmacro %}

{% block container %}
{% if prompt_for_survey %}
<div class="alert alert-info" role="alert">
  <p class="mt-3">Thanks for submitting {% if num_talks == 1 %}a talk{% else %}talks{% endif %}!
  In order to help us ensure a diverse and inclusive {{ g.conference.informal_name }},
  please consider filling out the <a href="{{ url_for("views.demographic_survey") }}">demographic
  survey</a>.</p>
  <p>You may <a href="{{ url_for("views.demographic_survey_opt_out") }}">opt
  out</a> to dismiss this message.</p>
</div>
{% endif %}
{% if prompt_for_bio %}
<div class="alert alert-info" role="alert">
  <p class="mt-3">Thanks for submitting {% if num_talks == 1 %}a talk{% else %}talks{% endif %}!
  Please add a <a href="{{ url_for("views.user_profile") }}">speaker biography</a> to your profile,
  for inclusion in the conference program.
  </p>
</div>
{% endif %}

{% macro talk_table(talks) %}
{% for talk in talks %}
  <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %}">
    <div class="col-md-7 talk">
      <a href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">{{ talk.title|truncate(100) }}</a>
      {{ vitals(talk) }}
    </div>
    <div class="col-md-5 text-right">
      Updated {{ talk.updated|timesince }}
      <a href="{{ url_for("views.edit_speakers", talk_id=talk.talk_id) }}" class="btn btn-outline-primary btn-sm ml-2">Manage Speakers</a>
      {% for label, cls, view in talk_actions[talk.state] %}
      <a href="{{ url_for(view, talk_id=talk.talk_id) }}" class="btn btn-outline-{{cls}} btn-sm">{{ label }}</a>
      {% endfor %}
    </div>
    {% if talk.has_anonymization_changes %}
    <div class="col-md-12 mt-2">
      <div class="alert alert-warning my-0 pt-1 pb-2" role="alert">
        <small>
        This talk has anonymization changes. Please <a href="{{ url_for("views.anonymized_talk", talk_id=talk.talk_id) }}">review
        the anonymized version</a>, and consider updating your talk for
        anonymous review.
        </small>
      </div>
    </div>
    {% endif %}
  </div>
{% endfor %}
{% endmacro %}

{% set has_proposed_talks = proposed_talks|length > 0 %}
{% set has_withdrawn_talks = withdrawn_talks|length > 0 %}

<div class="row py-3">
  <div class="col">
    <h3>{% if has_withdrawn_talks %}Proposed {% endif %}Talks:</h3>
    {% if has_proposed_talks %}
    {{ talk_table(proposed_talks) }}
    {% else %}
    <div class="row py-2 border-top border-right border-left border-bottom">
      <div class="col-md-12">
        <em>
          No talks yet.
          {% if g.conference.creating_proposals_allowed %}
            Why not <a href="{{ url_for("views.create_talk") }}">add one now?</a>
          {% endif %}
        </em>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% if g.conference.creating_proposals_allowed %}
<div class="row py-2">
  <div class="col text-right">
    <a class="btn btn-primary" href="{{ url_for("views.create_talk") }}">Add Talk</a>
  </div>
</div>
{% endif %}
{% if has_withdrawn_talks %}
<div class="row py-3">
  <div class="col">
    <h3 class="my-3">Withdrawn Talks:</h3>
    <p><em>Withdrawn talks will not be considered for inclusion in {{ g.conference.informal_name }}.</em></p>
    {{ talk_table(withdrawn_talks) }}
  </div>
</div>
{% endif %}

{% if invitations|length > 0 %}
  <div class="row py-3">
    <div class="col">
      <h3>Speaker Invitations:</h3>
    </div>
  </div>
  {% for invitation in invitations %}
    <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %}">
      <div class="col-md-9 talk">
        {{ invitation.talk.title|truncate(100) }}
        {{ vitals(invitation.talk) }}
      </div>
      <div class="col-md-3 text-right">
        {% for label, cls, view in speaker_actions[invitation.state] %}
        <a href="{{ url_for(view, talk_id=invitation.talk.talk_id) }}" class="btn btn-outline-{{cls}} btn-sm">{{ label }}</a>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
  <div class="row py-2">
    <div class="col text-right">
      <a class="btn btn-primary" href="{{ url_for("views.create_talk") }}">Add Talk</a>
    </div>
  </div>
{% endif %}
{% endblock %}